theme = "base16_transparent"

[editor]
line-number = "relative"
mouse = false
cursorline = true
true-color = true
popup-border = "popup"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]
