# ~/.config/helix/config.toml
theme = "carbonfox-bg-none"

[editor]
line-number = "absolute"
mouse = false
auto-save = true
auto-format = true
cursorline = true
true-color = true
popup-border = "popup"
end-of-line-diagnostics = "hint"
bufferline = "always"

[keys.normal]
C-y = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh open"

[editor.inline-diagnostics]
cursor-line = "error"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.statusline]
left = ["spinner", "mode", "version-control"]
center = ["read-only-indicator", "file-name", "file-modification-indicator"]
right = [
  "diagnostics",
  "selections",
  "register",
  "position",
  "file-encoding",
  "file-line-ending",
]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
